name = "MayhallJuliaRegistry"
uuid = "97282e19-24e7-4dff-b829-a65e033e877b"
repo = "git@github.com:nmayhall-vt/MayhallJuliaRegistry.git"
description = "My private registry"

[packages]
be646426-f34c-4536-b1d4-a45a9633e6db = { name = "PauliOperators", path = "P/PauliOperators" }
